### ISSUE TITLE
safari error

### ISSUE THREAD

**Issue by michaelenco** [TrustyFund/trusty-ui-vue#106]
после коммита https://github.com/TrustyFund/trusty-ui-vue/commit/1c95b00124f533c23ddfa0761f9fa7d8a37eb543 сафари [начал косячить](https://lut.im/KxfQXfJtUN/OxSHRmgfZNAsNyJE.png). Если я не ошибаюсь, то причина в [этом](https://github.com/TrustyFund/trusty-ui-vue/commit/1c95b00124f533c23ddfa0761f9fa7d8a37eb543#diff-2dad19ee289fcd76cc84c5f869f36fa2L4) изменении

**Comment by youaresofunny** [comment]
вернули скролл на нативный ( как было) - сейчас всё ок должно быть
