### ISSUE TITLE
Максимальая длина строки

### ISSUE THREAD

**Issue by ololokiras** [TrustyFund/trusty-ui-vue#122]
В мастере в линтере сейчас максимальная длина строки - 80. С соткой ещё был согласен, но неужели кто-то правда сидит на 486м? Давайте вернём сотку?

**Comment by roma219** [comment]
@ololokiras А причём здесь 486й? Вообще 80 - это мировой стандарт, код читабельнее становится. Ну да ладно. Почему убралась 100 непонятно, можешь вернуть и сделать PR.

**Comment by youaresofunny** [comment]
100 в мастере.. (и в vuex 100)
