### ISSUE TITLE
coinpage вёртска

### ISSUE THREAD

**Issue by ololokiras** [TrustyFund/trusty-ui-vue#125]
Нужна помощь по вёрстке в coinpage:

- [x] 1. привести к общему виду разделы Descriptions и Features.
- [x] 2. проверить скролл при выпадающих списках, бывает зависает при скролле вниз. Проверить на safari
- [x] 3. проверить округления значения market cap, его нужно привести в соответствие с cryptocompare

- [x] 4. Сделать полоски для блоков раз и навсегда адекватными. Бывает нет под нижним блоком, бывает двойная полоска 
![image](https://user-images.githubusercontent.com/17277287/38018322-220565a0-32a7-11e8-9bf9-746b9f2c705b.png) 
![image](https://user-images.githubusercontent.com/17277287/38018504-a42346f6-32a7-11e8-816b-11137673ca4f.png)

- [x] 5. Сделать отступ надписи Overview provided by cryptocompare.com больше от блоков и информацией

**Comment by roma219** [comment]
@ololokiras А 3й пункт имеет отношение к вёрстке? Округление задается Math.floor / Math.round/ Math.toFixed

**Comment by riffca** [comment]
@roma219 тут что то сделано в #112
чего там не хватает?

**Comment by riffca** [comment]
для PR

**Comment by roma219** [comment]
@riffca Это скорее к тебе вопрос

**Comment by ololokiras** [comment]
@riffca 
я ж отметил пунктами, по мере выполнения отмечай их и коммить в #124
