### ISSUE TITLE
Не видно scroll-bar

### ISSUE THREAD

**Issue by roma219** [TrustyFund/trusty-ui-vue#134]

**Comment by riffca** [comment]
@roma219 , уточни где его не видно?

**Comment by armaza** [comment]
@riffca У нас где то есть скрол бар ?!)

**Comment by riffca** [comment]
@hisinbox, а где то нужен скролл бар?

**Comment by roma219** [comment]
@riffca Во всем приложении, скролл бар элемента router_content

**Comment by riffca** [comment]
@roma219 на мобильных?

**Comment by roma219** [comment]
@riffca Нигде не видно, ни на мобиле, ни на компе. Это появилось после того, как вся прокрутка ушла в router_content

**Comment by riffca** [comment]
@roma219 iphone 5 показывает на мобильном полосу, и в инструментах разработчика с мобильным видом.

**Comment by roma219** [comment]
@riffca 5se и chrome os x (мобильный и обычный режим) - нигде нет

**Comment by roma219** [comment]
Вот из-за этого не видно:
![image](https://user-images.githubusercontent.com/4411295/38022449-1847c408-32b2-11e8-9a92-b53af849ac40.png)
