### ISSUE TITLE
Некорректные данные в профиле инкогнито

### ISSUE THREAD

**Issue by youaresofunny** [TrustyFund/trusty-ui-vue#136]
Нулевые значения в долларах для TOTAL FUND и в $VALUE
Нулевые 7DAYS CHANGE

![localhost_4000_ nexus 6p](https://user-images.githubusercontent.com/1954900/38016771-ba5a18c0-3278-11e8-9f0a-03260e4573b5.png)
![localhost_4000_ nexus 6p](https://user-images.githubusercontent.com/1954900/38016786-c822dc3a-3278-11e8-920f-996da0c33d5b.png)

**Comment by roma219** [comment]
@youaresofunny Вряд ли проблема связана с инкогнито, скорее нода, к которой подключилась прислала апдейты с нулевой ценой или что-то такое. акк hobb1t wss://bitshares.openledger.info/ws всё ок

**Comment by youaresofunny** [comment]
не было доллара в конфиге
