### ISSUE TITLE
Проверить 7D change

### ISSUE THREAD

**Issue by youaresofunny** [TrustyFund/trusty-ui-vue#138]
Сильно расходятся с https://coincheckup.com/

**Comment by armaza** [comment]
@youaresofunny Давайте сделаем 24HRS change пжл. И потом уже доделаем чтобы по клику менялись на разные периоды

**Comment by ololokiras** [comment]
У нас вообще неи 7D change

**Comment by ololokiras** [comment]
Сорян, не то понял

**Comment by roma219** [comment]
@youaresofunny Расходятся, потому что в своё время расчёт процентов был изменён с соотношения last/first на first/last, чтобы было похоже на проценты на bitshares. Поменял обратно и сделал 24h change.
