### ISSUE TITLE
Добавить расчет комиссий для ордеров

### ISSUE THREAD

**Issue by youaresofunny** [TrustyFund/trusty-ui-vue#151]
После мержа https://github.com/TrustyFund/vuex-bitshares/pull/46

Можно забрать комиссию через API.Parameters.getComission('limit_order_create')
Нужно умножить на кол-во ордеров и вывести в confirmTransaction

**Comment by roma219** [comment]
@youaresofunny Как вывести? типа надпись commission: 20 BTS или ? Не должно ли это происходить на этапе получения ордеров, чтобы они корректные получились? (чтобы не было ситуации когда ордер на продажу на всю сумму баланса и нет денег на комиссию)

**Comment by youaresofunny** [comment]
Там комиссии включены в ордеры, нужно просто вывести. Типа через отступ,  transaction fee {{fee}} BTS

**Comment by roma219** [comment]
Окей
