### ISSUE TITLE
Привести в порядок LOGIN

### ISSUE THREAD

**Issue by youaresofunny** [TrustyFund/trusty-ui-vue#158]
Нужно сделать как на SIGNUP

![image](https://user-images.githubusercontent.com/1954900/38134094-57368848-341a-11e8-9d88-45cfc3e58819.png)

![image](https://user-images.githubusercontent.com/1954900/38134100-5c0b6e56-341a-11e8-8773-de0ac5449a28.png)

**Comment by roma219** [comment]
@youaresofunny расстояние в месте кружков 2 и 3 идентично расстоянию в Sign Up
