### ISSUE TITLE
Инпуты компонентами

### ISSUE THREAD

**Issue by youaresofunny** [TrustyFund/trusty-ui-vue#16]
Селект
Текст эдит
Эдитбокс

**Comment by roma219** [comment]
Для селекта есть хорошая грамотная либа https://sagalbot.github.io/vue-select/ . Умеет многое из коробки (мультиселект, создание, удобная интеграция с вуексом)

**Comment by youaresofunny** [comment]
Здесь скорее визуальная подоплёка, завязать на vuex не так уж и сложно ручками, хотя можно и присмотреться (другой вопрос в том что 80% функционала указанной либы пока не нужно)

@riffca Присмотрись, мб сорсы полезно будет глянуть)
