### ISSUE TITLE
Правка scrollbar

### ISSUE THREAD

**Issue by ololokiras** [TrustyFund/trusty-ui-vue#172]
Скролл бар сломал всё на ПК. На скрине ubuntu

![image](https://user-images.githubusercontent.com/17277287/38160482-779da9f4-34f1-11e8-9f44-38e8415ef8f2.png)

в мобильном отображение в браузере тоже лютоват 
![image](https://user-images.githubusercontent.com/17277287/38160493-a916a7a6-34f1-11e8-8da2-67b333d6746c.png)

**Comment by youaresofunny** [comment]
https://github.com/TrustyFund/trusty-ui-vue/pull/177
