### ISSUE TITLE
Правки лендинга 

### ISSUE THREAD

**Issue by hisinbox** [TrustyFund/trusty-ui-vue#176]
Сломался плавный скрол по стрелкам внизу 

Поправить расстояние под заголовком How To Use (слишком маленькое, сделать как под остальными заголовками) 

Сделать иконки How To Use кликабельными, чтобы по клику скролило в нужное место

**Comment by youaresofunny** [comment]
Скролл поправил здесь: 
https://github.com/TrustyFund/trusty-ui-vue/pull/177
