### ISSUE TITLE
Установка submodule vuex-bitshares

### ISSUE THREAD

**Issue by ololokiras** [TrustyFund/trusty-ui-vue#18]
При установки репки на чистое окружение, не подгружается vuex-bitshares. Директория оказывается пустой.

**Comment by youaresofunny** [comment]
Это git submodule

Нужно либо клонировать рекурсивно (git clone --recursive)
Либо инициализировать после клонирования (git submodule init && git submodule update)

**Comment by ololokiras** [comment]
my bad
