### ISSUE TITLE
Установить минимальный порог для BTS и TRUSTY

### ISSUE THREAD

**Issue by youaresofunny** [TrustyFund/trusty-ui-vue#186]
TRUSTY: 1.4%
BTS: 0.8%

Показывать info toast с соответствующим текстом:
Minimum share of TRUSTY is 1.4%
Minimum share of BTS is 0.8%

**Comment by roma219** [comment]
@youaresofunny Когда показывать?

**Comment by youaresofunny** [comment]
@roma219 когда достигнут порог и он пытается еще уменьшить
