### ISSUE TITLE
Сбились колонки в профиле + еще пару правок

### ISSUE THREAD

**Issue by hisinbox** [TrustyFund/trusty-ui-vue#188]
- [x] Сбились стрелки справа от названий ассетов

- [x] Стрелка у сокращенного многоточием ассета  мельче остальных

- [ ] Колонка Share слишком прижата к колонке Value, в целом вроде место есть слева, можно колонки раздвинуть

- [x] Если  value меньше 10$, то все таки показывать один знак после точки

- [ ] колонки слева / справа должны быть ровно выровнены по краям кнопки manage fund

- [x] шрифты на manage fund должны быть как в кабинете

**Comment by youaresofunny** [comment]
Не актуально - будет новая верстка в pr к https://github.com/TrustyFund/trusty-ui-vue/issues/205
