### ISSUE TITLE
Deposit / Withdraw Openledger

### ISSUE THREAD

**Issue by youaresofunny** [TrustyFund/trusty-ui-vue#2]
Нужно подумать как это сделать так, чтобы любой мог подключить эти самые депозит и withdraw в свое vue приложение. @riffca есть идеи?

**Comment by youaresofunny** [comment]
Можно начать с переноса openledger crypto

**Comment by riffca** [comment]
Возможно добиться ясности в компонентах  и добавить набор итоговых  разработок в npm пакет.

**Comment by youaresofunny** [comment]
Может сделать это либой для vue? (С возможностью обернуть в любой дизайн)

**Comment by youaresofunny** [comment]
Хотя, вероятно, нет смысла делать это отдельно от авторзиации (в плане обособленностей пакетов)

**Comment by youaresofunny** [comment]
@riffca ?

**Comment by youaresofunny** [comment]
https://github.com/TrustyFund/trusty-ui-vue/pull/23
