### ISSUE TITLE
Проверить цены и volume ассетов в портфеле

### ISSUE THREAD

**Issue by youaresofunny** [TrustyFund/trusty-ui-vue#204]
Есть подозрение, что там что-то не так.

**Comment by armaza** [comment]
@youaresofunny и bitUSD не мог задень вырасти на 10% к USD

**Comment by youaresofunny** [comment]
https://github.com/TrustyFund/vuex-bitshares/commit/74643c802585d3ff827d12904c484a1dd4cd8290
