### ISSUE TITLE
Добавить тогл вида личного кабинета

### ISSUE THREAD

**Issue by hisinbox** [TrustyFund/trusty-ui-vue#205]
сначала маленькая правки - расстояние под кнопками до имени юзера должно быть такое же как расстояние под суммой портфеля

также убрать стрелочки справа от названий ассетов

теперь про тогл

будет два вида

первый вид включает три колонки
$PRICE 24H 7D

второй вид включает три колонки
$VALUE TOKENS SHARE

переключатель тогла в виде бледной надписи SHOW BALANCES справа над колонками (при нажатии меняется на SHOW PRICES) (при этом заголовки колонок нужно сделать белыми (как заголовок RECENT TRANSACTIONS, так как сейчас они почему то бледные)

**Comment by youaresofunny** [comment]
@roma219 можно сделать это в рамках https://github.com/TrustyFund/trusty-ui-vue/pull/193

**Comment by roma219** [comment]
@youaresofunny Ок, необходимы прояснения, что должно быть в колонках $price $value tokens ?

**Comment by armaza** [comment]
@roma219 Price - цена токена в долларах 
Value то же самое что-то сейчас 
Tokens количество токенов

**Comment by armaza** [comment]
@roma219 Все данные уже есть утрам в Системе 

Tokens используется для расчёта value 
Price - то же самое
