### ISSUE TITLE
Мелкие правки в разных местах приложения

### ISSUE THREAD

**Issue by hisinbox** [TrustyFund/trusty-ui-vue#212]
- [x] заменить шапку экрана COMPULSORY BACKUP на просто BACKUP
- [x] заменить название поля имени в рублёвом депозите на ENTER CARDHOLDER’S NAME
- [x] добавить в рублевые методы Raiffeisen card2card и VTB card2card и Rocket card2card
- [x] когда проблемы с обучение адреса для депозита вместо No address писать Try again later
- [x] при регистрации заменить текст замены имейа с .tf на .fund (name@doman.com > name.fund) и убрать слово funds в над суммой аккаунта

И обнови пжл тексты бота

**Comment by youaresofunny** [comment]
https://github.com/TrustyFund/trusty-ui-vue/pull/220
