### ISSUE TITLE
Мелкие правки часть 2

### ISSUE THREAD

**Issue by hisinbox** [TrustyFund/trusty-ui-vue#218]
Manage fund:
- [x] Неактивные кнопки на manage fund сделать значительно бледнее
- [x] Не вылезает тостер когда нажимаешь на минус TRUSTY после достижения минимума

Withdraw:
- [x] Поправить расположение примечания под полем суммы и писать текст с маленькой буквы ошибки (например если сумма не заполнена - то ENTER SUM)
- [x] текст ошибки заменять поверх примечания (а не второй строкой) 
- [x] поправить опечатку в insufficient и дописать insufficient funds, max X.XXX BTC (click to paste)
- [x] Обновить размер комиссии под кнопками на 0.0016 $

**Comment by youaresofunny** [comment]
https://github.com/TrustyFund/trusty-ui-vue/pull/223
