### ISSUE TITLE
Trusty app won't allow tutanota '@tuta.io' email addresses for signup

### ISSUE THREAD

**Issue by hisinbox** [TrustyFund/trusty-ui-vue#225]
Trusty app won't allow tutanota '@tuta.io' email addresses for signup, just fyi

**Comment by apasia-tech** [comment]
Since MX differs from actual domain - tutanota.de / tuta.io it can be the issue. Or maybe app has blacklisted .io domains. Let them get back to it, thanks for issue.

**Comment by youaresofunny** [comment]
Just registered with tutanote@tuta.io email name, looks like it works.

**Comment by youaresofunny** [comment]
Fixed
