### ISSUE TITLE
Deposit / Withdraw 

### ISSUE THREAD

**Issue by youaresofunny** [TrustyFund/trusty-ui-vue#24]
## Deposit 
- [ ] Openledger
- [ ] Trusty
## Withdraw
- [ ] Openledger
- [ ] Trusty

**Comment by riffca** [comment]
Сейчас там javascript классы(взятые из оригинального клиента). Которые содержат рабочую логику, но выглядят немного нагромождено.  В депозит отрабатывает получение адресов для openledger и blocktrades. Для withdraw по этим же сервисам, чтобы подключить и работало, необходимо подключить нужные данные и вывести во view.

**Comment by roma219** [comment]
Как минимум, нужно всё разносить логика <--> представление, сторонние шлюзы выносить в отдельные модули-сервисы. В компонентах (views) - по большей части должно быть только представление, основная логику надо выносить в экшены, сторонние сервисы-утилиты - в соответствующие папки.  В реакт версии какой-то лютый неподдерживаемый и нечитаемый код, поэтому от реакт-кода надо не избавляться, а просто делать сразу грамотно. 

Мне кажется, тактика - скопировать кучу реактовоского кода, сделать его вуешным и заставить как-то работать, а потом уже подумать, как бы сделать получше - не правильна. Надо изначально исходить из функционала той или иной части приложения, и исходя из этого формировать модули и сервисы, внутри которых уже как-то использовать наработки из реакт версии.

**Comment by riffca** [comment]
Не уверен на счет читаемости и поддерживаемости bitshares кода.  Мне кажется тут вопрос уровня вхождения. Что касается и тактики тоже.
В нашем приложении, мы же стремимся к наглядности и простоте, с чем я согласен. 
Проработать более детально код, разделить, сделать доступнее - отличная задача.
