### ISSUE TITLE
Доработка  компоненты Backup

### ISSUE THREAD

**Issue by roma219** [TrustyFund/trusty-ui-vue#27]
1) Переделать отображение вложенных страниц компонента роутером
![image](https://user-images.githubusercontent.com/4411295/36255693-ff807f92-128a-11e8-9760-2c506ded9a98.png)
Использовать для этого https://router.vuejs.org/en/essentials/nested-routes.html

2) На странице backup-verify при выборе слов необходимо, чтобы они пропадали из контейнера, откуда их выбираешь. Так же предусмотреть длинные слова/много слов - overflow контейнеров со словами.

3) Табличка "Try again" вылезает при загрузке любой из бэкап страниц.

4) Убрать вот это
![image](https://user-images.githubusercontent.com/4411295/36255929-d6df9284-128b-11e8-9262-648bed1942ba.png)

5) Переименовать computed getPhrase из index.vue в phrase (это переменная, т.е. существительная) и перенести её в data (это статические данные).

6) Переименовать имена vue файлов компоненты Backup в соответствие со стайл-гайдом https://vuejs.org/v2/style-guide/#Tightly-coupled-component-names-strongly-recommended
Заодно можно аналогично переименовать файлы всех остальных компонент.

7) Убрать modal из стора app. Это внутренняя логика компонента backup, пусть там и будет - то есть надо сделать в сторе компоненту backup, где и реализовать логику показа модальных окон (параметр в стейте, экшены, мутации). 

8) Убрать выставление тайтла компоненты header через store, вернуть предыдущий вариант через computed из $route.name.

Изменения вносить в данном PR: https://github.com/TrustyFund/trusty-ui-vue/pull/26

**Comment by riffca** [comment]
Зачем убирать modal из стор? Модальные  есть и в других местах. Ты предлагаешь все модальные окна делать внутри компонентов. Чем тебе не нравится идея стора с  необходимым страфом для приложения типо модального окна или хедера? Вот к примеру  на странице deposit trusty можно использовать header Title или на managePortfolio есть модальные окна.

**Comment by roma219** [comment]
@riffca Его надо не убрать из стора, а перенести в стор соответствующей компоненты, т.к. это часть её внутреннего состояния (нигде кроме как в бекапе эти модальные окна не могут быть показаны), и это нужно хранить в её же стейте. Если тебе хочется сделать более универсально - то можно сделать такой ui-компонент Modal, в который инфа о показе будет передаваться через slot, а показывать его через props, который значение будет брать из нужного геттера внутри самой компоненты. Его можно будет использовать в разных частях приложения. Если в будущем будет какое-то окно, которое может всплывать в любой части приложения, тогда надо будет делать в компоненте app параметр showThisModal: true/false и менять его при необходимости соотв. экшенами.

Что касается хедера, то лучше разделить показ хедера исходя из нейма роута и показ какой-то кастомщины в хедере, а не смешивать их, добавляя всякие вотчеры на роут и кучу логики в стор. То есть для реализации первого идеально подходит computed из $route.name. Если есть необходимость показать что-то еще, то тогда стоит сделать отдельный компонент стора header,  в котором сделать так, как ты сделал сейчас показ хедера - то есть экшены для назначения и убирания customTitle (но нужно ли это вообще?). И внутри хедера логика - если есть customTitle, показать его, если нет - просто title (условно).

**Comment by roma219** [comment]
https://github.com/TrustyFund/trusty-ui-vue/pull/26
