### ISSUE TITLE
webpack.prod.js не собирается

### ISSUE THREAD

**Issue by michaelenco** [TrustyFund/trusty-ui-vue#34]
скорее всего дело в es2015 + async/await

**Comment by youaresofunny** [comment]
Вроде уже собирается, @roma219 ты что-то правил?

**Comment by roma219** [comment]
@youaresofunny Нет

**Comment by youaresofunny** [comment]
¯\_(ツ)_/¯

**Comment by michaelenco** [comment]
не собирается, трэвис .dev собирает сейчас. Проблема с .prod билдом не решена

**Comment by youaresofunny** [comment]
@michaelenco но я только что сбилдил прод и выложил его на серв wtf?

Npm build ?

**Comment by michaelenco** [comment]
"npm run build" собирает по .dev конфигу. https://travis-ci.org/TrustyFund/trusty-ui-vue/builds/348131986#L976. И если ты про сервер на который указывает beta.trusty.fund, то там инстанс пока что запущен через "npm run dev".

**Comment by youaresofunny** [comment]
Нет, я про trusty.fund

А ты правил чтобы билд с дев конфига срабатывал?

**Comment by michaelenco** [comment]
да, чтобы весь ci цикл отладить

**Comment by youaresofunny** [comment]
Ок, нужно смотреть тогда .prod

**Comment by ololokiras** [comment]
Вроде запилил в #64

**Comment by youaresofunny** [comment]
:1st_place_medal:
