### ISSUE TITLE
Убрать скриншоты из папки проекта

### ISSUE THREAD

**Issue by roma219** [TrustyFund/trusty-ui-vue#36]
В папке style/screens картинок на 1.2мб. Не забывай, пожалуйста, их удалять после завершения работы над вёрсткой и сабмита PR.

**Comment by roma219** [comment]
@riffca Нет, просто незачем засорять папку проекта неиспользуемыми файлами.

**Comment by riffca** [comment]
@roma219 это уже в мастере

**Comment by roma219** [comment]
@riffca ok

**Comment by roma219** [comment]
@riffca На будущее - делай меншн issue через #<номер issue> в PR, чтобы было понятно какие issue закрывает pr и не накапливались сделанные.
