### ISSUE TITLE
User page (vuex part)

### ISSUE THREAD

**Issue by youaresofunny** [TrustyFund/trusty-ui-vue#5]
/user/{username}
Необходимо вывести список ассетов юзера, их value в $ и изменение цены за 7 дней

**Comment by youaresofunny** [comment]
Список ассетов юзера - portfolio, получает на вход те же пропсы что и управление портфелем (Manage Portfolio).

Желательно посмотреть как это реализовано в react версии, здесь есть несколько вариантов решения.

**Comment by roma219** [comment]
@youaresofunny А в плане дизайна-вёрстки как, есть какие-то макеты? или пока чисто набросок с функционалом

**Comment by youaresofunny** [comment]
Перенесу этот issue в новый реп с vuex
Здесь оставим задачи по переносу верстки и подключения к ней store.
