### ISSUE TITLE
Brainkey backup logic

### ISSUE THREAD

**Issue by youaresofunny** [TrustyFund/trusty-ui-vue#53]
Бэкап брейнкия будет вызываться на любом экране кроме home (в случае если этот бэкап еще не пройден). 
Факт бэкапа нужно хранить в cookie в формате brainkeyBackupDate: date

Что нужно сделать:
1. Добавить экран ввода пароля, этот экран будет показываться после 1 шага ( Continue to backup)
    По верстке и содержанию пока не понятно, за сим там нужен просто input и кнопка продолжить
    Юзер вводит свой пароль и в случае если всё ок, кнопка становится активна и он переходит на следующий шаг. (проверять можно через action unlockWallet )
2. На следующий экран (backup/phrase) нужно вывести brainkey юзера
3. На следующем экране (backup/verify) нужно проверять валидность ввода brainkey (на confirm) и отправлять на последний экран (backup/done)
4. На экране done нужно сделать возможность отмечать чек пункты и сделать кнопку FinishBackup активной только в случае если все пункты отмечены. (и записывать факт бэкапа в куку)
![image](https://user-images.githubusercontent.com/1954900/36961259-8a8a5a58-205b-11e8-9d10-f19cc1550d2c.png)
Вот это нужно выпилить с последнего экрана.

**Comment by armaza** [comment]
@youaresofunny Пжл установите себе кошелёк Bitcoin.com и посмотрите как это там реализовано - у нас практически идентично

**Comment by youaresofunny** [comment]
@armaza та часть которая требовала просмотра bitcoin.com уже готова (это в верстке было)
