### ISSUE TITLE
Вызов brainkey backup

### ISSUE THREAD

**Issue by ololokiras** [TrustyFund/trusty-ui-vue#62]
Прикрутить вызов brainkey backup на manage portfolio, deposit, withdraw, когда эти экраны будут готовы.

**Comment by youaresofunny** [comment]
Ждём это здесь:
https://github.com/TrustyFund/trusty-ui-vue/issues/61
https://github.com/TrustyFund/trusty-ui-vue/issues/24

**Comment by roma219** [comment]
Ждать готовностей экранов не надо, это делается через router meta поле (аналогично проверке на логин - Роману я уже объяснил этот момент).

**Comment by youaresofunny** [comment]
Ждать надо (чтобы протестить и закрыть PR)

**Comment by roma219** [comment]
Это можно протестить и без готового функционала менеджмента и тд. Просто не пускает на страницу менеджмента, и редиректит на бэкап, после него - на менеджмент.

**Comment by youaresofunny** [comment]
Это понятно, но нужно будет еще роуты на кнопки поставить и тп, к чему лишние действия? Эта задача на полчаса в любом случае, пусть висит и ждет своего часа)

**Comment by roma219** [comment]
Даже и роуты на кнопки не надо) просто по урлу перейти, на который в роутере мета needsBackup и всё  🇮🇩

**Comment by youaresofunny** [comment]
А, ну да, @ololokiras не ждем)
