### ISSUE TITLE
Разделение экрана в Backup verify

### ISSUE THREAD

**Issue by ololokiras** [TrustyFund/trusty-ui-vue#63]
Нужно растянуть верхнюю часть или придумать ещё какой-нибудь ход для того, что набранная фраза на этапе подтверждения brainkey частично не скрывалась как на скринах  
![image](https://user-images.githubusercontent.com/17277287/37202709-33ad951a-23c6-11e8-9431-fa6665d70e79.png)  здесь вообще целиком не влезает) 
![image](https://user-images.githubusercontent.com/17277287/37202746-5c25c206-23c6-11e8-8ffe-1cc5e824563b.png)

**Comment by ololokiras** [comment]
@riffca Благодарю за оперативность

**Comment by riffca** [comment]
@ololokiras напиши пожалуйста как дойти до этого шага с брейнкей? я прошел регистрацию у нас через signup, потом перешел на в ручную  на backup. Там, когда время пришло я вводил пароль при регистрации придуманный, но он не отрабатывал..

**Comment by ololokiras** [comment]
@riffca сейчас чекну с паролем что не так. А так, ты всё правильно делаешь.

**Comment by ololokiras** [comment]
@riffca Странно, но у меня получилось создать пользователя, ввести от него пароль и мне выдал brainkey фразу на этапе backup/phrase

**Comment by riffca** [comment]
![image](https://user-images.githubusercontent.com/16510189/37252210-4ff1c3f4-252e-11e8-886b-e8f79abeba81.png) у меня вот это постоянно вылазит. Я смотрю backup-brainkey ветку. Хорошо бы если кто то еще потестит

**Comment by ololokiras** [comment]
@riffca переведи сабмодуль в ту же ветку backup-brainkey. У меня удалось воспроизвести это, когда vuex-bitshares в master перевёл. Продублировал в телеграм на всякий случай

**Comment by riffca** [comment]
@ololokiras добавил растяжение поля

**Comment by roma219** [comment]
В этом контейнере есть прокрутка.

**Comment by riffca** [comment]
да она там есть

**Comment by riffca** [comment]
сделал по другому
