### ISSUE TITLE
Улучшить высоту контейнера с прокруткой

### ISSUE THREAD

**Issue by roma219** [TrustyFund/trusty-ui-vue#65]
Сейчас любая страница всегда имеет прокрутку независимого от того, влезает её содержимое в экран или нет, пример: 
![image](https://user-images.githubusercontent.com/4411295/37261161-3da1768e-25d5-11e8-91d9-4452ac61e5dc.png)

Необходимо избавиться от этого, нужно сделать чтобы App.vue занимал всегда всю доступную высоту и ширину и имел прокрутку в случае когда его контент не влезает в него (сейчас прокрутку у body происходит). Это также предотвратит разрушение вёрстки в случае какого-либо неформатного контента (слишком длинная строка и т.п.).

**Comment by riffca** [comment]
Проблема была в padding, который заменял пространство header, если бы последний не был фиксированным.

**Comment by roma219** [comment]
@riffca Там можно обойтись и без таких паддингов, на флексе сделать, чтобы не-хедер часть просто растягивалась наоставшееся место. В любом случае надо, чтобы прокрутка была внутри App.vue, а не всего документа (чтобы нельзя было лоадер прокрутить).

**Comment by riffca** [comment]
@roma219 лоадер сейчас не прокручивается. @youaresofunny посмотри пожалуйста актуальность прокрутки на app, а не документе.

**Comment by roma219** [comment]
#75
