### ISSUE TITLE
Кнопки скрола справа на ПК версии  при клике скролят криво - нужно отцентровать

### ISSUE THREAD

**Issue by hisinbox** [TrustyFund/trusty-ui-vue#90]

**Comment by riffca** [comment]
@hisinbox нужно чтобы картинка как доскролили была по центру экрана?

**Comment by youaresofunny** [comment]
1. нужно сдвинуть начало следующего экрана чтобы его не было видно (на всех экранах проявляется)
![selection_234](https://user-images.githubusercontent.com/1954900/38598046-7daf582c-3d63-11e8-9647-5af1e379481f.png)
2. Добавить скролл на последний экран 
![selection_235](https://user-images.githubusercontent.com/1954900/38598078-9d98c934-3d63-11e8-9e66-3898bf030d2a.png)
3. Немного сдвинуть вниз текст чтобы смотрелось адекватно
![selection_236](https://user-images.githubusercontent.com/1954900/38598089-ada45d98-3d63-11e8-97df-193935e695f4.png)
